"""Typed contracts shared by feature, model, validation, and report modules."""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd


@dataclass(frozen=True)
class FeatureMatrix:
    """A numeric feature matrix with row identity and availability masks."""

    values: pd.DataFrame
    identifiers: pd.DataFrame
    availability: pd.DataFrame
    feature_names: tuple[str, ...]

    def __post_init__(self) -> None:
        rows = len(self.values)
        if len(self.identifiers) != rows or len(self.availability) != rows:
            raise ValueError("Feature matrix tables must have equal row counts")
        if tuple(self.values.columns) != self.feature_names:
            raise ValueError("feature_names must match values columns")
        if tuple(self.availability.columns) != self.feature_names:
            raise ValueError("Availability mask must match feature columns")
        numeric = self.values.to_numpy(dtype=float)
        available = self.availability.to_numpy(dtype=bool)
        if not np.isfinite(numeric[available]).all():
            raise ValueError("Available feature values must be finite")


@dataclass
class RoleDiscoveryResult:
    """Probabilistic role assignments, fitted state, and diagnostics."""

    assignments: pd.DataFrame
    candidate_metrics: pd.DataFrame
    selected_k: int
    selected_covariance_type: str
    model: Any
    transformer: Any
    scaler: Any
    pca: Any
    diagnostics: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class MetricSet:
    """Binary-probability evaluation metrics."""

    roc_auc: float
    pr_auc: float
    expected_calibration_error: float
    brier_score: float
    rows: int
    positives: int


@dataclass(frozen=True)
class MetricGateResult:
    """Decision from comparing attention with a role-aware baseline."""

    accepted: bool
    selected_layer: str
    tasks: dict[str, dict[str, MetricSet]]
    spearman_with_legacy: float | None
    message: str


@dataclass(frozen=True)
class ArtifactManifest:
    """Files generated by one pipeline execution."""

    output_root: Path
    files: tuple[Path, ...]
    hashes: dict[str, str]
    schema_version: str
    metadata: dict[str, Any] = field(default_factory=dict)
